name: Build test
on:
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: bash ci.sh llvm
    - name: Build binutils
      run: bash ci.sh binutils
    - name: Zipping toolchain
      run: zip -r $GITHUB_WORKSPACE/RvClang-19.1.5.zip $GITHUB_WORKSPACE/RvClang/
    - name: Tar toolchain
      run: tar -czvf $GITHUB_WORKSPACE/RvClang-19.1.5.tar.gz $GITHUB_WORKSPACE/RvClang/
